export const SET_AUTHENTICATED='SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED='SET_UNAUTHENTICATED';
export const SET_USER='SET_USER';
export const LOADING_USER='LOADING_USER';

export const SET_ERRORS='SET_ERRORS';
export const CLEAR_ERRORS='CLEAR_ERRORS';

export const SET_ALBUMS='GET_ALBUMS';
export const SET_CURRENT_ALBUM='SET_CURRENT_ALBUM';
export const LOADING_ALBUMS='LOADING_ALBUMS';

export const SET_ARTISTS='SET_ARTISTS';
export const LOADING_ARTISTS='LOADING_ARTISTS';